package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Sushiwok Tests")
    void generatedTest() {
        step("https://sushiwok.ru/voronezh/menu/rolly/", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://sushiwok.ru/voronezh/menu/rolly/'", () ->
            open("https://sushiwok.ru/voronezh/menu/rolly/"));
            sleep(3000);

        step("Page title should have text 'Just a moment...'", () -> {
            String expectedTitle = "Just a moment...";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
            sleep(3000);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://sushiwok.ru/voronezh/menu/rolly/'", () ->
            open("https://sushiwok.ru/voronezh/menu/rolly/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}